channels:
  - pytorch
  - conda-forge
  - defaults
  - anaconda
dependencies:
  - python=3.9
  - pip=21.1
  - fire=0.4
  - cudatoolkit=11.3
  - pytorch=1.10
  - torchvision=0.9.1
  - xarray=0.17
  - scikit-learn=0.24.2
  - numpy=1.20.2
  - netcdf4=1.5.6
  - matplotlib=3.4.2
  - cartopy=0.19.0
  - cartopy_offlinedata=0.2.4
  - tabulate=0.8.9
  - xrft=0.3.0
  - numpy_groupies=0.9.13
  - pip:
    - pytorch-lightning==1.4.9
    - omegaconf
    - einops
    - hydra-submitit-launcher
    - opencv-python==4.5.2.52
    - hydra-core
    - kornia
    - pyepsg
